import {mkdir,writeFile} from 'node:fs/promises';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import path from 'node:path';
const destination=path.resolve(process.argv[2]||path.join('backups',new Date().toISOString().replace(/[:.]/g,'-')));
await mkdir(destination,{recursive:true});
const args=['--format=custom','--schema=daybook','--file',path.join(destination,'daybook.pg.dump')];
if(process.env.DATABASE_URL)args.push('--dbname',process.env.DATABASE_URL);
await promisify(execFile)('pg_dump',args);
await writeFile(path.join(destination,'RESTORE.txt'),'Stop Daybook and reminders before restoring. Restore daybook.pg.dump into the intended PostgreSQL database with pg_restore (the archive contains only the daybook schema). Attachments and OpenAI settings are included. Protect the dump because it contains the API key if configured. Check the target database carefully before using --clean. Restart Daybook. .env.local is not included.\n');
console.log('Backup saved to '+destination);
